version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn test --coverage
      - run: ./node_modules/.bin/coveralls < ./coverage/lcov.info
  flow:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn flow-typed install
      - run: yarn flow
  lint:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: docker build -t bp2018hg1/tobito:$CIRCLE_WORKFLOW_ID -t bp2018hg1/tobito:latest .
      - run: docker push bp2018hg1/tobito:$CIRCLE_WORKFLOW_ID
      - run: docker push bp2018hg1/tobito:latest
  deploy_staging:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $STAGING_DEPLOY_FINGERPRINT
      - run: ssh root@$STAGING_DEPLOY_HOST "cd $STAGING_DEPLOY_HOME; ./deploy tobito bp2018hg1/tobito:$CIRCLE_WORKFLOW_ID"
  deploy_production:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $PRODUCTION_DEPLOY_FINGERPRINT
      - run: ssh root@$PRODUCTION_DEPLOY_HOST "cd $PRODUCTION_DEPLOY_HOME; ./deploy tobito bp2018hg1/tobito:$CIRCLE_WORKFLOW_ID"
  deploy_agent:
    docker:
      - image: circleci/openjdk:latest-node
    steps:
      - checkout
      - run: wget -O ./dfc_compiler.jar https://github.com/arne-z/BachelorThesis/releases/download/0.1.1/dfc_compiler.jar
      - run: yarn install
      - run: node ./utility/generatePhrasesForBothGetArtifactsIntents.js 
      - run: java -jar ./dfc_compiler.jar ./Agent/Tobito.dfc
      - run: echo $GOOGLE_CERT_FILE_64 | base64 --decode > ./googleKey.json
      - run: node ./utility/importAgent.js --dir ./src-gen --key ./googleKey.json --pid projects/newagent-bdb60


workflows:
  version: 2
  pipeline:
    jobs:
      - test
      - flow
      - lint
      - deploy_agent
      - build:
          requires:
            - test
            - flow
            - lint
      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - hold_production_deploy:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_production:
          requires:
            - hold_production_deploy
          filters:
            branches:
              only: master
